# ClusterIssuer configuration for cert-manager using Let's Encrypt production server.
# This sets up ACME HTTP-01 challenge through an Ingress with class 'nginx'.
# Certificates issued will be associated with the email disney@timsmans.be.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: disney@timsmans.be
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
