global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'raspberry-pis'
    static_configs:
      - targets: ['192.168.1.101:8000']
        labels:
          instance: 'pi-01'
      - targets: ['192.168.1.102:8000']
        labels:
          instance: 'pi-02'
